from datetime import timedelta
from django.forms import ValidationError
from django.utils import timezone
import uuid
from django.contrib.auth.models import User
from django.db import models

def validate_room_name(value):
    """
    Validates that the room name contains no spaces or special characters.
    """
    if " " in value or not value.isalnum():
        raise ValidationError("Room name cannot contain spaces or special characters.")

class Room(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    name = models.CharField(max_length=255, unique=True, validators=[validate_room_name])
    title = models.CharField(max_length=255, default="")
    admins = models.ManyToManyField(
        User, through="RoomAdmin", related_name="admin_rooms"
    )
    users = models.ManyToManyField(User, through="RoomMembership")

class DirectMessage(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sent_messages"
    )
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="received_messages"
    )
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["sender", "receiver"], name="unique_dm_pair"
            )
        ]

class RoomAdmin(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)

class RoomMembership(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)

class InviteLink(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    room = models.OneToOneField(Room, on_delete=models.CASCADE)
    link = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    expires_at = models.DateTimeField()

class Message(models.Model):
    id = models.AutoField(primary_key=True)  # Autogenerated ID as primary key
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
