# Generated by Django 5.0.6 on 2024-05-10 19:52

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[chat.models.validate_room_name]),
        ),
        migrations.AlterField(
            model_name='roomadmin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
