# Generated by Django 4.2.13 on 2024-06-29 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_onlinestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invitelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='chat.room'),
        ),
    ]
